{% set name = "pytest-catchlog" %}
{% set version = "1.2.2" %}
{% set hash_type = "sha256" %}
{% set hash = "4be15dc5ac1750f83960897f591453040dff044b5966fe24a91c2f7d04ecfcf0" %}
{% set ext = "zip" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pytest

test:
  requires:
    - pytest
  imports:
    - pytest_catchlog
  commands:
    - py.test --help

about:
  home: https://github.com/eisensheng/pytest-catchlog
  license: MIT
  license_file: LICENSE.txt
  summary: py.test plugin to catch log messages. This is a fork of pytest-capturelog.

extra:
  recipe-maintainers:
    - nicoddemus
