travis:
  secure:
    BINSTAR_TOKEN: yXHUgXNliBITpGWqq/O2DnSiOW95munuayzUX4Oyik4ZvjoxsIkZ9W+lifwIAlDEeyiadVUuRihfoYkItWjHh00w8XVsogXzlQ8h5slLdirJgOOffKYkP/ieRA0Wj21A3gqeC82c1oV2OnVvMEmPtuCg2K2UIAnsOGvvIYOL+QMNag1/sjf0Jn4azy0UIkiEiQAt/dAAKh+GmxOPk3DPn9cOYq0RVuvsQJzJX7iUNH9wocvi9Vc+qCXTx/l2iL9L9ZDwsu7L5KS5JvurAsmPu5oby3wIowPQHbJyI8nrw+Xs97f9ZMJy49Nxckje2BDCny4VQuZ4DSDIeuOG2Y9cnlpU0Ehfon6WX0/MJPzE8qpEZLZcpdRW08X2Pn9PuBF94YQ52ddiMwd66he/ZhvYsjT1wq/ylUsIi8p+Zoi23qJA7WrvfKd7NdKMUUeYpi6t5+vfVV7NDzrZeshCxlAi/o8UwsyMY4x1d7+Q1xcoV+dOmt7pq6+MTa4JsZXDulDquvLJhG1DmI/rSmM5mCGP7g/n6NQkpj8ixwYcqTrLncfElUSQASMl+LCy3vBAiBMrs2aSGcIt5UbhjZPzHB/j1jGl0mjSNSYTSj35va9fHNkEu5vNY8zoJOIrBwgQ18N1UZdtO1RTKKaPNu1un3NdsTj80jm0/BJL1RymWgyCdR4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
