travis:
  secure:
    BINSTAR_TOKEN: pOYbdffKnq9e13RyntQ9QE2g272rGeF6vJysSSWVjFdFH4Bg38EKeC7GfUbgKWOeru6pD8brj31ygYx5zwQs9F0NQP70g3EOpYxUoiZze51OsFPx8cew2wR0oxnkCbCAAzaGDQH67dy0fUX+eAWS16xzn2MKOrgNGTZCWUjjbAX7RkyLlU0Uy75/+zHDXEWGppj7ollQip/on1uxD9BkLZGHKB+OHGpS7PZ3uVJQycjezyGtpxNTBcjxwGC6Z1o+jtq0Y2NuXXldhJqzNLW0ckxQnhj7PeXqyurGnP2yGIFTZPTdFgo+pn8Uyfvj3YC2a3X2gXRDKFyf4N8+E32RUZksa4JtcdLgENUC2IUgjTweIxpdtuLhijHtRR0SlwzjQ2Mt0vT5LZvOBT40oo7QnJEhvHOlxb26JbpgEFq5r2F2gzoNnd0UUAT7ZWJPiF3uB6cM0IYQhHggvzBYAqXyNyXxp56Ra5klBAjMq+c49lAh5dyWzUO08zDCWjk4B3dXCMBXJRhlilC5wZllNyAJTYT0RL7NmrtRnyVVWzXBTNLWwTCpXmTdFlzcC3rdu4wx/+j3fnnTeNvrksHLi0nvZYgUH6sxi6c135PSE2htoItONobHkBSZKLl/X8eYnAodWNWAH9aorJ402YQQ8PSPChj7XHCECLkpMzpV4iQ9G0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
